language: php

services:
  - mysql
  - elasticsearch

sudo: true

matrix:
  fast_finish: true
  include:
    - php: 7.2

install:
  - composer install --prefer-dist

before_script:
  - sleep 10

script:
  - vendor/bin/phpstan.phar analyse src --level=1
  - vendor/bin/phpunit -c phpunit-ci.xml
