language: php

jdk:
  - oraclejdk8

services:
  - mysql

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: true

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: ES_VERSION="6.5.0"

    - php: 7.2
      env: ES_VERSION="6.5.0"

env:
  global:
    - ES_TEST_HOST=http://localhost:9200
    - JAVA_HOME="/usr/lib/jvm/java-8-oracle/jre"

before_install:
  - sudo update-java-alternatives -s java-8-oracle
  - ./travis/download_and_run_es.sh
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"

install:
  - composer install --prefer-dist

before_script:
  - php util/RestSpecRunner.php
  - php util/EnsureClusterAlive.php

script:
  - composer run-script phpcs; fi
  - composer run-script phpstan
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - vendor/bin/phpunit -c phpunit-integration.xml --group sync $PHPUNIT_FLAGS
